// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muwbta.Domain.Abilities;
using Muwbta.Domain.Inhabitants;
using Muwbta.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Muwbta.Persistence.Migrations
{
    [DbContext(typeof(MuwbtaDbContext))]
    [Migration("20260906174336_WorldMaps")]
    partial class WorldMaps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Muwbta.Domain.Abilities.Ability", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<long?>("CastTimePulses")
                        .HasColumnType("bigint")
                        .HasColumnName("cast_time_pulses");

                    b.Property<int?>("CooldownGroup")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_group");

                    b.Property<long>("CooldownPulses")
                        .HasColumnType("bigint")
                        .HasColumnName("cooldown_pulses");

                    b.Property<int>("CostType")
                        .HasColumnType("integer")
                        .HasColumnName("cost_type");

                    b.Property<int>("CostValue")
                        .HasColumnType("integer")
                        .HasColumnName("cost_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<List<AbilityEffectSpec>>("Effects")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("effects");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Path")
                        .HasColumnType("integer")
                        .HasColumnName("path");

                    b.Property<int>("TargetingType")
                        .HasColumnType("integer")
                        .HasColumnName("targeting_type");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("unlock_level");

                    b.HasKey("Key")
                        .HasName("pk_abilities");

                    b.HasIndex("TargetingType")
                        .HasDatabaseName("ix_abilities_targeting_type");

                    b.HasIndex("Path", "UnlockLevel")
                        .HasDatabaseName("ix_abilities_path_unlock_level");

                    b.ToTable("abilities", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Accounts.AccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("scope");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_access_tokens");

                    b.HasIndex("AccountId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_access_tokens_account");

                    b.ToTable("access_tokens", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("BanReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ban_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<string>("LastLoginAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_login_address");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("MutedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("muted_until");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RegisteredFromAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("registered_from_address");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_username");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Accounts.AdminAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("After")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("before");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TargetAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_account_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit");

                    b.HasIndex("TargetAccountId", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_admin_audit_target");

                    b.ToTable("admin_audit", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Building.ContentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("action");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entity_kind");

                    b.HasKey("Id")
                        .HasName("pk_content_audit");

                    b.HasIndex("EntityKind", "EntityKey", "At")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_content_audit_entity");

                    b.ToTable("content_audit", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("CombatState")
                        .HasColumnType("integer")
                        .HasColumnName("combat_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentTarget")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_target");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.PrimitiveCollection<List<string>>("Flags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("flags");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.PrimitiveCollection<List<string>>("IgnoredNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ignored_names");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("path");

                    b.Property<long>("PlaytimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("playtime_seconds");

                    b.Property<string>("RespawnRoomKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("respawn_room_key");

                    b.Property<int>("RestState")
                        .HasColumnType("integer")
                        .HasColumnName("rest_state");

                    b.Property<string>("RoomKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("room_key");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_name");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Inhabitants.MobTemplate", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<List<MobAttack>>("Attacks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attacks");

                    b.Property<int>("BaseGold")
                        .HasColumnType("integer")
                        .HasColumnName("base_gold");

                    b.Property<Dictionary<string, object>>("BaseStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("base_stats");

                    b.Property<int>("BaseXp")
                        .HasColumnType("integer")
                        .HasColumnName("base_xp");

                    b.Property<Dictionary<string, object>>("Behavior")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("behavior");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<List<Dictionary<string, object>>>("Loot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("loot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("WanderIntervalPulses")
                        .HasColumnType("integer")
                        .HasColumnName("wander_interval_pulses");

                    b.HasKey("Key")
                        .HasName("pk_mob_templates");

                    b.ToTable("mob_templates", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Items.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContainerItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_item_id");

                    b.Property<int?>("EquippedSlot")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_slot");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<Guid?>("OwnerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_character_id");

                    b.Property<Dictionary<string, object>>("ResolvedStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resolved_stats");

                    b.Property<string>("RoomKey")
                        .HasColumnType("text")
                        .HasColumnName("room_key");

                    b.Property<Dictionary<string, decimal>>("SpawnMultipliers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("spawn_multipliers");

                    b.Property<Guid?>("SpawnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("spawner_id");

                    b.Property<Dictionary<string, object>>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_name");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_item_instances");

                    b.HasIndex("OwnerCharacterId")
                        .HasDatabaseName("ix_item_instances_owner_character_id");

                    b.HasIndex("RoomKey")
                        .HasDatabaseName("ix_item_instances_room_key");

                    b.ToTable("item_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_instance_location", "(num_nonnulls(owner_character_id, container_item_id, room_key) = 1)");
                        });
                });

            modelBuilder.Entity("Muwbta.Domain.Items.ItemTemplate", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int?>("AttackDelayPulses")
                        .HasColumnType("integer")
                        .HasColumnName("attack_delay_pulses");

                    b.Property<string>("AttackVerb")
                        .HasColumnType("text")
                        .HasColumnName("attack_verb");

                    b.Property<Dictionary<string, object>>("BaseStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("base_stats");

                    b.Property<int>("BaseValue")
                        .HasColumnType("integer")
                        .HasColumnName("base_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DrinkValue")
                        .HasColumnType("integer")
                        .HasColumnName("drink_value");

                    b.Property<int?>("FoodValue")
                        .HasColumnType("integer")
                        .HasColumnName("food_value");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsLightSource")
                        .HasColumnType("boolean")
                        .HasColumnName("is_light_source");

                    b.Property<bool>("IsLore")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lore");

                    b.Property<bool>("IsNoDrop")
                        .HasColumnType("boolean")
                        .HasColumnName("is_no_drop");

                    b.Property<bool>("IsQuestItem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_quest_item");

                    b.Property<bool>("IsTwoHanded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_two_handed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Paths")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("paths");

                    b.Property<string>("Slots")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("slots");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Key")
                        .HasName("pk_item_templates");

                    b.ToTable("item_templates", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Quests.CharacterQuest", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("QuestKey")
                        .HasColumnType("text")
                        .HasColumnName("quest_key");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TimesCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("times_completed");

                    b.HasKey("CharacterId", "QuestKey")
                        .HasName("pk_character_quests");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_quests_character_id");

                    b.HasIndex("CharacterId", "Status")
                        .HasDatabaseName("ix_character_quests_character_id_status")
                        .HasFilter("status = 'Active'");

                    b.ToTable("character_quests", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Quests.Quest", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_start");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Dictionary<string, string>>("Dialogue")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dialogue");

                    b.Property<string>("GiverMobKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("giver_mob_key");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_repeatable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Paths")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("paths");

                    b.PrimitiveCollection<List<string>>("PrerequisiteQuestKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("prerequisite_quest_keys");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("integer")
                        .HasColumnName("required_count");

                    b.Property<string>("RequiredItemKey")
                        .HasColumnType("text")
                        .HasColumnName("required_item_key");

                    b.Property<string>("RewardFlagKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reward_flag_key");

                    b.Property<int>("RewardGold")
                        .HasColumnType("integer")
                        .HasColumnName("reward_gold");

                    b.Property<int>("RewardItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("reward_item_count");

                    b.Property<string>("RewardItemKey")
                        .HasColumnType("text")
                        .HasColumnName("reward_item_key");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer")
                        .HasColumnName("reward_xp");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TurninMobKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turnin_mob_key");

                    b.Property<string>("ZoneKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_key");

                    b.HasKey("Key")
                        .HasName("pk_quests");

                    b.HasIndex("GiverMobKey")
                        .HasDatabaseName("ix_quests_giver_mob_key");

                    b.HasIndex("TurninMobKey")
                        .HasDatabaseName("ix_quests_turnin_mob_key");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Spawning.Spawner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("FightsAtLevel")
                        .HasColumnType("integer")
                        .HasColumnName("fights_at_level");

                    b.Property<string>("NameModifier")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name_modifier");

                    b.Property<int>("RespawnSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("respawn_seconds");

                    b.PrimitiveCollection<List<string>>("RoomKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("room_keys");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<int>("TemplateKind")
                        .HasColumnType("integer")
                        .HasColumnName("template_kind");

                    b.Property<bool?>("Wanders")
                        .HasColumnType("boolean")
                        .HasColumnName("wanders");

                    b.Property<string>("ZoneKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_key");

                    b.HasKey("Id")
                        .HasName("pk_spawners");

                    b.HasIndex("ZoneKey")
                        .HasDatabaseName("ix_spawners_zone_key");

                    b.ToTable("spawners", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.GameConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("BlockedWords")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasDefaultValue("")
                        .HasColumnName("blocked_words");

                    b.Property<string>("Canon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("canon");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("name");

                    b.Property<string>("StartingRoomKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("starting_room_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WelcomeMessage")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("welcome_message");

                    b.PrimitiveCollection<List<string>>("WorldKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("world_keys");

                    b.HasKey("Key")
                        .HasName("pk_game_configurations");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_game_configurations_active")
                        .HasFilter("is_active");

                    b.ToTable("game_configurations", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.Room", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EditorX")
                        .HasColumnType("integer")
                        .HasColumnName("editor_x");

                    b.Property<int?>("EditorY")
                        .HasColumnType("integer")
                        .HasColumnName("editor_y");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.PrimitiveCollection<List<string>>("Grid")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("grid");

                    b.Property<string>("Legend")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("legend");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<string>("ZoneKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("zone_key");

                    b.HasKey("Key")
                        .HasName("pk_rooms");

                    b.HasIndex("ZoneKey")
                        .HasDatabaseName("ix_rooms_zone_key");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.RoomExit", b =>
                {
                    b.Property<string>("FromRoomKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("from_room_key");

                    b.Property<string>("Direction")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<string>("RefusalMessage")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refusal_message");

                    b.Property<string>("RequiredFlagKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("required_flag_key");

                    b.Property<string>("RequiredItemKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("required_item_key");

                    b.Property<string>("ToRoomKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("to_room_key");

                    b.HasKey("FromRoomKey", "Direction")
                        .HasName("pk_room_exits");

                    b.HasIndex("ToRoomKey")
                        .HasDatabaseName("ix_room_exits_to_room_key");

                    b.ToTable("room_exits", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.World", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<string>("Multipliers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("multipliers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Key")
                        .HasName("pk_worlds");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.WorldMap", b =>
                {
                    b.Property<string>("WorldKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("world_key");

                    b.Property<string>("Svg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("svg");

                    b.HasKey("WorldKey")
                        .HasName("pk_world_maps");

                    b.ToTable("world_maps", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.Zone", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer")
                        .HasColumnName("max_level");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_level");

                    b.Property<string>("Multipliers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("multipliers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("WorldKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("world_key");

                    b.HasKey("Key")
                        .HasName("pk_zones");

                    b.HasIndex("WorldKey")
                        .HasDatabaseName("ix_zones_world_key");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("Muwbta.Domain.Accounts.AccessToken", b =>
                {
                    b.HasOne("Muwbta.Domain.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_tokens_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Muwbta.Domain.Characters.Character", b =>
                {
                    b.HasOne("Muwbta.Domain.Accounts.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_accounts_account_id");

                    b.OwnsOne("Muwbta.Domain.Characters.AttributeSet", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Agility");

                            b1.Property<int>("Insight");

                            b1.Property<int>("Might");

                            b1.Property<int>("Resolve");

                            b1.Property<int>("Vitality");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1
                                .ToJson("attributes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId")
                                .HasConstraintName("fk_characters_characters_character_id");
                        });

                    b.OwnsOne("Muwbta.Domain.Characters.Vitals", "Vitals", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Focus");

                            b1.Property<int>("FocusMax");

                            b1.Property<int>("Health");

                            b1.Property<int>("HealthMax");

                            b1.Property<int>("Hunger");

                            b1.Property<int>("Stamina");

                            b1.Property<int>("StaminaMax");

                            b1.Property<int>("Thirst");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1
                                .ToJson("vitals")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId")
                                .HasConstraintName("fk_characters_characters_character_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Vitals")
                        .IsRequired();
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.Room", b =>
                {
                    b.HasOne("Muwbta.Domain.Worlds.Zone", "Zone")
                        .WithMany("Rooms")
                        .HasForeignKey("ZoneKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_zones_zone_key");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.RoomExit", b =>
                {
                    b.HasOne("Muwbta.Domain.Worlds.Room", "FromRoom")
                        .WithMany("Exits")
                        .HasForeignKey("FromRoomKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_exits_rooms_from_room_key");

                    b.Navigation("FromRoom");
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.Zone", b =>
                {
                    b.HasOne("Muwbta.Domain.Worlds.World", "World")
                        .WithMany("Zones")
                        .HasForeignKey("WorldKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zones_worlds_world_key");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Muwbta.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.Room", b =>
                {
                    b.Navigation("Exits");
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.World", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Muwbta.Domain.Worlds.Zone", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
